#spring:
 # datasource:
  #  username: root
   # password:
  #  url:jdbc: mysql://localhost:3306/pfe
   # driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa:
   # show-sdl: true
    #hibernate:
    #  ddl-auto: update
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect